version: '3'

services:
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/app/quotesbackend/django_static
      - ./docker/nginx/production:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /tmp/acme_challenge:/tmp/acme_challenge
    depends_on:
      - quotesbackend
    image: quotes:nginx
  quotesbackend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/quotesbackend/Dockerfile
    entrypoint: /app/docker/quotesbackend/wsgi-entrypoint.sh
    volumes:
      - .:/app
      - static_volume:/app/quotesbackend/django_static
    expose:
      - 8000
    image: quotes:quotesbackend

volumes:
  static_volume: {}