version: '3'

services:
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/app/backend/django_static
      - ./docker/nginx/production:/etc/nginx/conf.d
      - ./docker/nginx/certbot/conf:/etc/letsencrypt
      - ./docker/nginx/certbot/www:/var/www/certbot
    depends_on:
      - quotesbackend
    image:
      - quotes:nginx
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./docker/nginx/cerrtbot/conf:/etc/letsencrypt
      - ./docker/nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/quotesbackend/Dockerfile
    entrypoint: /app/docker/quotesbackend/wsgi-entrypoint.sh
    volumes:
      - .:/app
      - static_volume:/app/quotesbackend/django_static
    expose:
      - 8000
    image: quotes:quotesbackend

volumes:
  static_volume: {}