# Generated by Django 4.1.3 on 2022-11-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='quote_text',
            new_name='quote',
        ),
        migrations.DeleteModel(
            name='QuotesList',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ManyToManyField(to='quotes.quote'),
        ),
    ]
