# Generated by Django 4.1.3 on 2022-11-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_quote_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='quotes',
        ),
    ]
